In [34]:
#Author: Anita Camlic
#This will be a rundown / practice of the linear algebra that you can do with the numpy library

import numpy as np

#MATRIX MULTIPLICATION
#(m x n)(n x r) = (m x r) for multiplication, the two inner dimensions must be equal
a = np.ones((2,3))
b = np.ones((3,8))

#demonstrating using the matrix multiplication function in numpy
# np.matmul(matrix1 , matrix2)
c = np.matmul(a,b)
print('dimension of new matrix after multiplication: ' + str(np.shape(c))) #should be 2 x 8

#demonstrating how to find the determinant using numpy
#we already know that the determinant of the identitiy matrix is one, so lets check that
# np.linalg.det(matrix), matrix must have dimensions (n x n) (must be a square matrix)
a = np.identity(5)

#checking if it is equal to one,then printing the result
np.linalg.det(a) == 1
print('determinant of the identity matrix: ' + str(np.linalg.det(a)))

#demonstrating how to find the dot product of two vectors
#for dot products, the vectors must be the same shape/dimensions
# np.dot(vector1 , vector2)
a = np.array([1,2,3]) #shape: (1,3)
b = np.array([3,2,1]) #shape: (1,3)
c = np.array([4,5,6]) #shape: (1,3)

#the dot product function below should return (3*1) + (2*2) + (3*1) = (3) + (4) + (3) = 10

print('dot product: ' + str(np.dot(a,b)))

#demonstrating how to find the inner product using numpy
# the dot product is a type of inner product. The inner product is more of a generalized term. Both are important
#in this example, the dot product and the inner product of vectors a and b should yield the same answer
# np.inner( vector1 , vector2)

print('inner product: ' + str(np.inner(a,b)))

#demonstrating how to find the outer product using numpy
#If u & v are vectors of the same dimension, then the outer product = u * Transpose(v)
#In the example below it will result in a matrix
# np.outer(vector1 , vector2)

print('outer product: \n' + str(np.outer(a,b)))

#MATRIX ADDITION
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.ones((3,3))

#demonstrating using the add function
#to add two matrices together, you shold use the add function, you can only add matrices of the same dimension
# np.add(matrix1 , matrix2)
print('matrix addition result: \n' + str(np.add(A,B)))

#MATRIX SUBTRACTION
#demonstrating the subtract function
#to subract two matrices from each other, you should use the subtract function, you can only subtract matrices of the same dimension
#np.subtract(matrix1 , matrix2)  = matrix1 - matrix2
print('matrix subtraction result: \n' + str(np.subtract(A,B)))

#MATRIX PRODUCTS
#Demonstrating how to do multiplication of matrices
#we will use the matmul function
#keeping it simple with (2*2) arrays
#np.matmul(matrix1 , matrix2) 

A = np.array([[2,2],[2,2]])
B = np.array([[1,2],[3,4]])

print('matrix A:')
print(A)
print('matrix B:')
print(B)

C = np.matmul(A,B)
print('A * B:')
print(C)








dimension of new matrix after multiplication: (2, 8)
determinant of the identity matrix: 1.0
dot product: 10
inner product: 10
outer product: 
[[3 2 1]
 [6 4 2]
 [9 6 3]]
matrix addition result: 
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
matrix subtraction result: 
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
matrix A:
[[2 2]
 [2 2]]
matrix B:
[[1 2]
 [3 4]]
A * B:
[[ 8 12]
 [ 8 12]]
